version: 2

before:
  hooks:
    - npm ci --prefix frontend
    - npm run build --prefix frontend

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - arm64
      - amd64
    ignore:
      - goos: linux
        goarch: arm64
      - goos: darwin
        goarch: amd64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
